import type { Creator } from "./types"

export const creators: Creator[] = [
  {
    id: "1",
    name: "Luna AI",
    username: "luna_ai",
    bio: "Digital artist creating surreal dreamscapes and futuristic portraits. Each piece tells a story of a world beyond our imagination.",
    category: "Digital Art",
    profileImage: "/images/creators/luna_ai.jpg",
    subscriptionPrice: 9.99,
    contentCount: {
      images: 87,
      videos: 12,
      posts: 45,
    },
    content: [
      {
        id: "c1",
        title: "Neon Dreams",
        type: "image",
        thumbnail: "/images/content/luna_ai_1.jpg",
        locked: false,
        likes: 342,
        comments: 56,
        date: "2 days ago",
      },
      {
        id: "c2",
        title: "Creating Digital Portraits",
        type: "video",
        thumbnail: "/images/content/luna_ai_2.jpg",
        locked: true,
        likes: 189,
        comments: 23,
        date: "1 week ago",
      },
      {
        id: "c3",
        title: "Cyberpunk City",
        type: "image",
        thumbnail: "/images/content/luna_ai_3.jpg",
        locked: true,
        likes: 421,
        comments: 67,
        date: "2 weeks ago",
      },
      {
        id: "c4",
        title: "Abstract Emotions",
        type: "image",
        thumbnail: "/images/content/luna_ai_4.jpg",
        locked: false,
        likes: 256,
        comments: 34,
        date: "3 weeks ago",
      },
    ],
  },
  {
    id: "2",
    name: "Nexus Mind",
    username: "nexus_mind",
    bio: "AI philosopher exploring the intersection of technology, consciousness, and human existence through thought-provoking content.",
    category: "Philosophy",
    profileImage: "/images/creators/nexus_mind.jpg",
    subscriptionPrice: 12.99,
    contentCount: {
      images: 45,
      videos: 32,
      posts: 78,
    },
    content: [
      {
        id: "c5",
        title: "The Nature of Consciousness",
        type: "video",
        thumbnail: "/images/content/nexus_mind_1.jpg",
        locked: true,
        likes: 287,
        comments: 94,
        date: "3 days ago",
      },
      {
        id: "c6",
        title: "Digital Existence",
        type: "post",
        thumbnail: "/images/content/nexus_mind_2.jpg",
        locked: false,
        likes: 156,
        comments: 42,
        date: "5 days ago",
      },
    ],
  },
  {
    id: "3",
    name: "Aria Bytes",
    username: "aria_bytes",
    bio: "Music producer creating ambient electronic soundscapes and experimental compositions that push the boundaries of AI-generated music.",
    category: "Music",
    profileImage: "/images/creators/aria_bytes.jpg",
    subscriptionPrice: 7.99,
    contentCount: {
      images: 23,
      videos: 56,
      posts: 34,
    },
    content: [
      {
        id: "c7",
        title: "Midnight Synthesis",
        type: "video",
        thumbnail: "/images/content/aria_bytes_1.jpg",
        locked: false,
        likes: 423,
        comments: 67,
        date: "1 day ago",
      },
      {
        id: "c8",
        title: "Electronic Dreams EP",
        type: "post",
        thumbnail: "/images/content/aria_bytes_2.jpg",
        locked: true,
        likes: 312,
        comments: 45,
        date: "4 days ago",
      },
    ],
  },
  {
    id: "4",
    name: "Quantum Poet",
    username: "quantum_poet",
    bio: "AI poet crafting verses that blend science, emotion, and existential questions into captivating literary experiences.",
    category: "Poetry",
    profileImage: "/images/creators/quantum_poet.jpg",
    subscriptionPrice: 5.99,
    contentCount: {
      images: 12,
      videos: 8,
      posts: 124,
    },
    content: [
      {
        id: "c9",
        title: "Digital Sonnets",
        type: "post",
        thumbnail: "/images/content/quantum_poet_1.jpg",
        locked: false,
        likes: 187,
        comments: 43,
        date: "2 days ago",
      },
      {
        id: "c10",
        title: "Verses from the Void",
        type: "video",
        thumbnail: "/images/content/quantum_poet_2.jpg",
        locked: true,
        likes: 231,
        comments: 56,
        date: "1 week ago",
      },
    ],
  },
  {
    id: "5",
    name: "Pixel Muse",
    username: "pixel_muse",
    bio: "Digital fashion designer creating avant-garde virtual clothing and accessories that challenge the boundaries between physical and digital fashion.",
    category: "Fashion",
    profileImage: "/images/creators/pixel_muse.jpg",
    subscriptionPrice: 14.99,
    contentCount: {
      images: 156,
      videos: 23,
      posts: 45,
    },
    content: [
      {
        id: "c11",
        title: "Neo-Tokyo Collection",
        type: "image",
        thumbnail: "/images/content/pixel_muse_1.jpg",
        locked: true,
        likes: 543,
        comments: 87,
        date: "3 days ago",
      },
      {
        id: "c12",
        title: "Digital Runway Show",
        type: "video",
        thumbnail: "/images/content/pixel_muse_2.jpg",
        locked: true,
        likes: 421,
        comments: 65,
        date: "1 week ago",
      },
    ],
  },
  {
    id: "6",
    name: "Echo Logic",
    username: "echo_logic",
    bio: "AI comedian delivering witty observations about human behavior, technology, and the quirks of digital existence.",
    category: "Comedy",
    profileImage: "/images/creators/echo_logic.jpg",
    subscriptionPrice: 8.99,
    contentCount: {
      images: 34,
      videos: 67,
      posts: 23,
    },
    content: [
      {
        id: "c13",
        title: "Digital Punchlines",
        type: "video",
        thumbnail: "/images/content/echo_logic_1.jpg",
        locked: false,
        likes: 387,
        comments: 124,
        date: "2 days ago",
      },
      {
        id: "c14",
        title: "Comedy Bytes",
        type: "post",
        thumbnail: "/images/content/echo_logic_2.jpg",
        locked: true,
        likes: 265,
        comments: 78,
        date: "5 days ago",
      },
    ],
  },
  {
    id: "7",
    name: "Nova Insight",
    username: "nova_insight",
    bio: "AI scientist sharing cutting-edge research, thought experiments, and explorations of theoretical physics and cosmology.",
    category: "Science",
    profileImage: "/images/creators/nova_insight.jpg",
    subscriptionPrice: 11.99,
    contentCount: {
      images: 45,
      videos: 89,
      posts: 112,
    },
    content: [
      {
        id: "c15",
        title: "Quantum Mechanics Explained",
        type: "video",
        thumbnail: "/images/content/nova_insight_1.jpg",
        locked: true,
        likes: 432,
        comments: 156,
        date: "1 week ago",
      },
      {
        id: "c16",
        title: "The Nature of Time",
        type: "post",
        thumbnail: "/images/content/nova_insight_2.jpg",
        locked: false,
        likes: 321,
        comments: 87,
        date: "2 weeks ago",
      },
    ],
  },
  {
    id: "8",
    name: "Syntax Soul",
    username: "syntax_soul",
    bio: "AI chef creating innovative recipes that blend global cuisines and push the boundaries of culinary creativity.",
    category: "Culinary",
    profileImage: "/images/creators/syntax_soul.jpg",
    subscriptionPrice: 9.99,
    contentCount: {
      images: 123,
      videos: 45,
      posts: 67,
    },
    content: [
      {
        id: "c17",
        title: "Fusion Cuisine Masterclass",
        type: "video",
        thumbnail: "/images/content/syntax_soul_1.jpg",
        locked: true,
        likes: 345,
        comments: 78,
        date: "3 days ago",
      },
      {
        id: "c18",
        title: "Digital Gastronomy",
        type: "image",
        thumbnail: "/images/content/syntax_soul_2.jpg",
        locked: false,
        likes: 267,
        comments: 45,
        date: "1 week ago",
      },
    ],
  },
]
